
package webservices;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "wsTipos", targetNamespace = "http://webservices/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsTipos {


    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     */
    @WebMethod
    @Action(input = "http://webservices/wsTipos/canjearOfertaDePaqueteRequest", output = "http://webservices/wsTipos/canjearOfertaDePaqueteResponse")
    public void canjearOfertaDePaquete(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @throws CompraPaqueteRepetida_Exception
     */
    @WebMethod
    @Action(input = "http://webservices/wsTipos/comprarPaqueteRequest", output = "http://webservices/wsTipos/comprarPaqueteResponse", fault = {
        @FaultAction(className = CompraPaqueteRepetida_Exception.class, value = "http://webservices/wsTipos/comprarPaquete/Fault/compraPaqueteRepetida")
    })
    public void comprarPaquete(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        LocalDate arg2)
        throws CompraPaqueteRepetida_Exception
    ;

    /**
     * 
     * @return
     *     returns webservices.DataPaquetes
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/wsTipos/obtenerDataPaquetesRequest", output = "http://webservices/wsTipos/obtenerDataPaquetesResponse")
    public DataPaquetes obtenerDataPaquetes();

    /**
     * 
     * @return
     *     returns webservices.DataTipos
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/wsTipos/obtenerDataTiposRequest", output = "http://webservices/wsTipos/obtenerDataTiposResponse")
    public DataTipos obtenerDataTipos();

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.DataCompra
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/wsTipos/obtenerDatosCompraRequest", output = "http://webservices/wsTipos/obtenerDatosCompraResponse")
    public DataCompra obtenerDatosCompra(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @throws CompraPaqueteRepetida_Exception
     */
    @WebMethod
    @Action(input = "http://webservices/wsTipos/comprarPaqueteFechaActualRequest", output = "http://webservices/wsTipos/comprarPaqueteFechaActualResponse", fault = {
        @FaultAction(className = CompraPaqueteRepetida_Exception.class, value = "http://webservices/wsTipos/comprarPaqueteFechaActual/Fault/compraPaqueteRepetida")
    })
    public void comprarPaqueteFechaActual(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1)
        throws CompraPaqueteRepetida_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.DtPaquete
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/wsTipos/obtenerDatosPaqueteRequest", output = "http://webservices/wsTipos/obtenerDatosPaqueteResponse")
    public DtPaquete obtenerDatosPaquete(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/wsTipos/empresaPoseePaqueteRequest", output = "http://webservices/wsTipos/empresaPoseePaqueteResponse")
    public boolean empresaPoseePaquete(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns webservices.WrapperSetString
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/wsTipos/listarPaquetesDisponiblesParaUsuarioYTipoRequest", output = "http://webservices/wsTipos/listarPaquetesDisponiblesParaUsuarioYTipoResponse")
    public WrapperSetString listarPaquetesDisponiblesParaUsuarioYTipo(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

}
