
package webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

import com.trabajouy.controllers.Consumir;

import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "wsTiposService", targetNamespace = "http://webservices/", wsdlLocation = "http://localhost:9128/wsTipos?wsdl")
public class WsTiposService
    extends Service
{

    private final static URL WSTIPOSSERVICE_WSDL_LOCATION;
    private final static WebServiceException WSTIPOSSERVICE_EXCEPTION;
    private final static QName WSTIPOSSERVICE_QNAME = new QName("http://webservices/", "wsTiposService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
        	Consumir genURL = new Consumir();
            url = new URL(genURL.getProperties("url") + "wsTipos?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSTIPOSSERVICE_WSDL_LOCATION = url;
        WSTIPOSSERVICE_EXCEPTION = e;
    }

    public WsTiposService() {
        super(__getWsdlLocation(), WSTIPOSSERVICE_QNAME);
    }

    public WsTiposService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSTIPOSSERVICE_QNAME, features);
    }

    public WsTiposService(URL wsdlLocation) {
        super(wsdlLocation, WSTIPOSSERVICE_QNAME);
    }

    public WsTiposService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSTIPOSSERVICE_QNAME, features);
    }

    public WsTiposService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsTiposService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WsTipos
     */
    @WebEndpoint(name = "wsTiposPort")
    public WsTipos getWsTiposPort() {
        return super.getPort(new QName("http://webservices/", "wsTiposPort"), WsTipos.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsTipos
     */
    @WebEndpoint(name = "wsTiposPort")
    public WsTipos getWsTiposPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices/", "wsTiposPort"), WsTipos.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSTIPOSSERVICE_EXCEPTION!= null) {
            throw WSTIPOSSERVICE_EXCEPTION;
        }
        return WSTIPOSSERVICE_WSDL_LOCATION;
    }

}
