
package webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

import com.trabajouy.controllers.Consumir;

import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "wsUsuariosService", targetNamespace = "http://webservices/", wsdlLocation = "http://localhost:9128/wsUsuarios?wsdl")
public class WsUsuariosService
    extends Service
{

    private final static URL WSUSUARIOSSERVICE_WSDL_LOCATION;
    private final static WebServiceException WSUSUARIOSSERVICE_EXCEPTION;
    private final static QName WSUSUARIOSSERVICE_QNAME = new QName("http://webservices/", "wsUsuariosService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
        	Consumir genURL = new Consumir();
            url = new URL(genURL.getProperties("url") + "wsUsuarios?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSUSUARIOSSERVICE_WSDL_LOCATION = url;
        WSUSUARIOSSERVICE_EXCEPTION = e;
    }

    public WsUsuariosService() {
        super(__getWsdlLocation(), WSUSUARIOSSERVICE_QNAME);
    }

    public WsUsuariosService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSUSUARIOSSERVICE_QNAME, features);
    }

    public WsUsuariosService(URL wsdlLocation) {
        super(wsdlLocation, WSUSUARIOSSERVICE_QNAME);
    }

    public WsUsuariosService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSUSUARIOSSERVICE_QNAME, features);
    }

    public WsUsuariosService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsUsuariosService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WsUsuarios
     */
    @WebEndpoint(name = "wsUsuariosPort")
    public WsUsuarios getWsUsuariosPort() {
        return super.getPort(new QName("http://webservices/", "wsUsuariosPort"), WsUsuarios.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsUsuarios
     */
    @WebEndpoint(name = "wsUsuariosPort")
    public WsUsuarios getWsUsuariosPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices/", "wsUsuariosPort"), WsUsuarios.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSUSUARIOSSERVICE_EXCEPTION!= null) {
            throw WSUSUARIOSSERVICE_EXCEPTION;
        }
        return WSUSUARIOSSERVICE_WSDL_LOCATION;
    }

}
