
package webservices;

import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "wsUsuarios", targetNamespace = "http://webservices/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsUsuarios {


    /**
     * 
     * @param arg1
     * @param fileName
     * @return
     *     returns byte[]
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/wsUsuarios/getFileRequest", output = "http://webservices/wsUsuarios/getFileResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://webservices/wsUsuarios/getFile/Fault/IOException")
    })
    public byte[] getFile(
        @WebParam(name = "fileName", partName = "fileName")
        String fileName,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1)
        throws IOException_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     * @param arg7
     * @param arg8
     * @throws Exception_Exception
     */
    @WebMethod
    @Action(input = "http://webservices/wsUsuarios/ingresarEmpresaRequest", output = "http://webservices/wsUsuarios/ingresarEmpresaResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://webservices/wsUsuarios/ingresarEmpresa/Fault/Exception")
    })
    public void ingresarEmpresa(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5,
        @WebParam(name = "arg6", partName = "arg6")
        String arg6,
        @WebParam(name = "arg7", partName = "arg7")
        String arg7,
        @WebParam(name = "arg8", partName = "arg8")
        String arg8)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     * @param arg7
     * @throws Exception_Exception
     */
    @WebMethod
    @Action(input = "http://webservices/wsUsuarios/ingresarPostulanteRequest", output = "http://webservices/wsUsuarios/ingresarPostulanteResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://webservices/wsUsuarios/ingresarPostulante/Fault/Exception")
    })
    public void ingresarPostulante(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        XMLGregorianCalendar arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5,
        @WebParam(name = "arg6", partName = "arg6")
        String arg6,
        @WebParam(name = "arg7", partName = "arg7")
        String arg7)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg10
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     * @param arg7
     * @param arg8
     * @param arg9
     * @param nickname
     * @return
     *     returns boolean
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/wsUsuarios/ingresarOfertaRequest", output = "http://webservices/wsUsuarios/ingresarOfertaResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://webservices/wsUsuarios/ingresarOferta/Fault/Exception")
    })
    public boolean ingresarOferta(
        @WebParam(name = "Nickname", partName = "Nickname")
        String nickname,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        DtHorario arg4,
        @WebParam(name = "arg5", partName = "arg5")
        int arg5,
        @WebParam(name = "arg6", partName = "arg6")
        XMLGregorianCalendar arg6,
        @WebParam(name = "arg7", partName = "arg7")
        String arg7,
        @WebParam(name = "arg8", partName = "arg8")
        String arg8,
        @WebParam(name = "arg9", partName = "arg9")
        WrapperSetString arg9,
        @WebParam(name = "arg10", partName = "arg10")
        String arg10)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @throws Exception_Exception
     */
    @WebMethod
    @Action(input = "http://webservices/wsUsuarios/ingresarDatosPostulacionRequest", output = "http://webservices/wsUsuarios/ingresarDatosPostulacionResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://webservices/wsUsuarios/ingresarDatosPostulacion/Fault/Exception")
    })
    public void ingresarDatosPostulacion(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        XMLGregorianCalendar arg4,
    	@WebParam(name="arg5",partName="arg5")
		String arg5)
        throws Exception_Exception
        
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.DtUsuario
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/wsUsuarios/mostrarDatosUsuarioRequest", output = "http://webservices/wsUsuarios/mostrarDatosUsuarioResponse")
    public DtUsuario mostrarDatosUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.DtOfertaLaboral
     * @throws NoExisteOferta_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/wsUsuarios/seleccionarOfertaLaboralRequest", output = "http://webservices/wsUsuarios/seleccionarOfertaLaboralResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://webservices/wsUsuarios/seleccionarOfertaLaboral/Fault/Exception")
    })
    public DtOfertaLaboral seleccionarOfertaLaboral(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws NoExisteOferta_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.WrapperSetString
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/wsUsuarios/listarOfertasIngresadasRequest", output = "http://webservices/wsUsuarios/listarOfertasIngresadasResponse")
    public WrapperSetString listarOfertasIngresadas(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @return
     *     returns webservices.WrapperSetString
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/wsUsuarios/listarEmpresasRequest", output = "http://webservices/wsUsuarios/listarEmpresasResponse")
    public WrapperSetString listarEmpresas();

    /**
     * 
     * @return
     *     returns webservices.WrapperListString
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/wsUsuarios/listarUsuariosRequest", output = "http://webservices/wsUsuarios/listarUsuariosResponse")
    public WrapperListString listarUsuarios();

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.DtPostulante
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/wsUsuarios/getDataPostulanteRequest", output = "http://webservices/wsUsuarios/getDataPostulanteResponse")
    public DtPostulante getDataPostulante(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.DtEmpresa
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/wsUsuarios/getDataEmpresaRequest", output = "http://webservices/wsUsuarios/getDataEmpresaResponse")
    public DtEmpresa getDataEmpresa(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     * @param arg7
     * @param arg8
     * @param arg9
     */
    @WebMethod
    @Action(input = "http://webservices/wsUsuarios/editarDatosBasicosRequest", output = "http://webservices/wsUsuarios/editarDatosBasicosResponse")
    public void editarDatosBasicos(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5,
        @WebParam(name = "arg6", partName = "arg6")
        XMLGregorianCalendar arg6,
        @WebParam(name = "arg7", partName = "arg7")
        String arg7,
        @WebParam(name = "arg8", partName = "arg8")
        String arg8,
        @WebParam(name = "arg9", partName = "arg9")
        String arg9);

    /**
     * 
     * @return
     *     returns webservices.DataOfertas
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/wsUsuarios/listarOfertasLaboralesRequest", output = "http://webservices/wsUsuarios/listarOfertasLaboralesResponse")
    public DataOfertas listarOfertasLaborales();

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.WrapperSetString
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/wsUsuarios/obtenerOfertasDeEmpresaRequest", output = "http://webservices/wsUsuarios/obtenerOfertasDeEmpresaResponse")
    public WrapperSetString obtenerOfertasDeEmpresa(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.DataOfertas
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/wsUsuarios/listarOfertasPorKeywordRequest", output = "http://webservices/wsUsuarios/listarOfertasPorKeywordResponse")
    public DataOfertas listarOfertasPorKeyword(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.DataOfertaDAO
     */
    @WebMethod(operationName = "ObtenerOfertasFinalizadas")
    @WebResult(partName = "return")
    @Action(input = "http://webservices/wsUsuarios/ObtenerOfertasFinalizadasRequest", output = "http://webservices/wsUsuarios/ObtenerOfertasFinalizadasResponse")
    public DataOfertaDAO obtenerOfertasFinalizadas(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws NoExisteOferta_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.OfertaDAO
     */
    @WebMethod(operationName = "ObtenerUnaOfertaFinalizada")
    @WebResult(partName = "return")
    @Action(input = "http://webservices/wsUsuarios/ObtenerUnaOfertaFinalizadaRequest", output = "http://webservices/wsUsuarios/ObtenerUnaOfertaFinalizadaResponse")
    public OfertaDAO obtenerUnaOfertaFinalizada(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws NoExisteOferta_Exception
    ;
    /**
     * 
     * @return
     *     returns webservices.WrapperSetString
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/wsUsuarios/listarTiposDePublicacionRequest", output = "http://webservices/wsUsuarios/listarTiposDePublicacionResponse")
    public WrapperSetString listarTiposDePublicacion();

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.DataPostulacionDAO
     */
    @WebMethod(operationName = "ObtenerPostulacionesOferta")
    @WebResult(partName = "return")
    @Action(input = "http://webservices/wsUsuarios/ObtenerPostulacionesOfertaRequest", output = "http://webservices/wsUsuarios/ObtenerPostulacionesOfertaResponse")
    public DataPostulacionDAO obtenerPostulacionesOferta(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws NoExisteOferta_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.DataPostulacionDAO
     */
    @WebMethod(operationName = "ObtenerPostulacionesUsuario")
    @WebResult(partName = "return")
    @Action(input = "http://webservices/wsUsuarios/ObtenerPostulacionesUsuarioRequest", output = "http://webservices/wsUsuarios/ObtenerPostulacionesUsuarioResponse")
    public DataPostulacionDAO obtenerPostulacionesUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws NoExisteOferta_Exception
    ;
    
    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns webservices.PostulacionDAO
     */
    @WebMethod(operationName = "ObtenerUnaPostulacionUsuario")
    @WebResult(partName = "return")
    @Action(input = "http://webservices/wsUsuarios/ObtenerUnaPostulacionUsuarioRequest", output = "http://webservices/wsUsuarios/ObtenerUnaPostulacionUsuarioResponse")
    public PostulacionDAO obtenerUnaPostulacionUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
    	@WebParam(name = "arg1", partName = "arg1")
    	String arg1)
        throws NoExisteOferta_Exception
    ;

    /**
     * 
     * @return
     *     returns webservices.WrapperSetString
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/wsUsuarios/listarKeywordsRequest", output = "http://webservices/wsUsuarios/listarKeywordsResponse")
    public WrapperSetString listarKeywords();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://webservices/wsUsuarios/finalizarOfertaRequest", output = "http://webservices/wsUsuarios/finalizarOfertaResponse")
    public void finalizarOferta(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @return
     *     returns webservices.WrapperSetString
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/wsUsuarios/listarPostulantesRequest", output = "http://webservices/wsUsuarios/listarPostulantesResponse")
    public WrapperSetString listarPostulantes();

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     */
    @WebMethod
    @Action(input = "http://webservices/wsUsuarios/elegirOrdenRequest", output = "http://webservices/wsUsuarios/elegirOrdenResponse")
    public void elegirOrden(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        int arg2);

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/wsUsuarios/esSeguidorRequest", output = "http://webservices/wsUsuarios/esSeguidorResponse")
    public boolean esSeguidor(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://webservices/wsUsuarios/agregarVisitaRequest", output = "http://webservices/wsUsuarios/agregarVisitaResponse")
    public void agregarVisita(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     */
    @WebMethod
    @Action(input = "http://webservices/wsUsuarios/followRequest", output = "http://webservices/wsUsuarios/followResponse")
    public void follow(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns webservices.DtUsuario
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/wsUsuarios/iniciarSesionRequest", output = "http://webservices/wsUsuarios/iniciarSesionResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://webservices/wsUsuarios/iniciarSesion/Fault/Exception")
    })
    public DtUsuario iniciarSesion(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/wsUsuarios/existeUsuarioRequest", output = "http://webservices/wsUsuarios/existeUsuarioResponse")
    public boolean existeUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/wsUsuarios/existeEmailRequest", output = "http://webservices/wsUsuarios/existeEmailResponse")
    public boolean existeEmail(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     */
    @WebMethod
    @Action(input = "http://webservices/wsUsuarios/unfollowRequest", output = "http://webservices/wsUsuarios/unfollowResponse")
    public void unfollow(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/wsUsuarios/writeImgRequest", output = "http://webservices/wsUsuarios/writeImgResponse")
    public String writeImg(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        byte[] arg3);
    
    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.DataOfertas
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/wsUsuarios/buscarPorFiltroOfertasLaboralesRequest", output = "http://webservices/wsUsuarios/buscarPorFiltroOfertasLaboralesResponse")
    public DataOfertas buscarPorFiltroOfertasLaborales(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);
    
    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.DataEmpresas
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/wsUsuarios/buscarPorFiltroEmpresasRequest", output = "http://webservices/wsUsuarios/buscarPorFiltroEmpresasResponse")
    public DataEmpresas buscarPorFiltroEmpresas(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    
    /**
     * 
     * @param arg0
     * @param arg1
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/wsUsuarios/agregarOfertaFavoritaRequest", output = "http://webservices/wsUsuarios/agregarOfertaFavoritaResponse")
    public void agregarOfertaFavorita(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1)
    ;

}
